#!/bin/bash
mkdir -p ${HOME}/.simonsays

docker run -it --rm \
    --name simonsays \
    -v "$(pwd):/project" \
    -v "${HOME}/.simonsays/helm:/root/.helm" \
    -v "${HOME}/.kube:/root/.kube" \
    -v "${HOME}/.aws:/root/.aws" \
    -e "AWS_PROFILE=${AWS_PROFILE}" \
    -e "AWS_REGION=${AWS_REGION}" \
    -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
    -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
    jonmeyer/node-aws-ci \
    "$@" 